image: gcc

build:
  stage: build
  script: g++ virna.cpp -o virna
  artifacts:
    paths:
      - virna

test:
  stage: test
  script:
    - chmod +x ./vir-gitlab.sh
    - ./vir-gitlab.sh ./test/main g++
    - chmod +x ./test/main
    - ./test/main
